import {
  Award,
  Briefcase,
  Calendar,
  Camera,
  Code,
  Globe,
  GraduationCap,
  Heart,
  Languages,
  Lightbulb,
  Mail,
  MapPin,
  Music,
  Phone,
  Plane,
  Star,
  Target,
  User,
  type LucideIcon,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  globe: Globe,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  star: Star,
  heart: Heart,
  award: Award,
  user: User,
  code: Code,
  languages: Languages,
  camera: Camera,
  music: Music,
  plane: Plane,
  target: Target,
  lightbulb: Lightbulb,
  calendar: Calendar,
}
